// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for CleanupFunction
 */
export interface CleanupFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/cleanup.
 */
export class CleanupFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: CleanupFunctionProps) {
    super(scope, id, {
      description: 'src/cleanup.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/cleanup.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}